spring:
  kafka:
    listener:
      observation-enabled: true
    template:
      observation-enabled: true
  application:
    name: delivery-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

springdoc:
  packages-to-scan: com.fooddelivery.delivery,com.fooddelivery.common.dto.governmentid

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 3000
      circuitbreaker:
        enabled: true
        alphanumeric-ids: true

resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
    instances:
      restaurant-service:
        baseConfig: default
      customer-service:
        baseConfig: default
      wallet-service:
        baseConfig: default
      mapsintegration:
        baseConfig: default
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      restaurant-service:
        baseConfig: default
      customer-service:
        baseConfig: default
      wallet-service:
        baseConfig: default
      mapsintegration:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
    instances:
      restaurant-service:
        baseConfig: default
      customer-service:
        baseConfig: default
      wallet-service:
        baseConfig: default
      mapsintegration:
        baseConfig: default

verification:
  vahan:
    api:
      url: "https://api.mock-vahan.gov.in/rc/verify"
      key: "mock-api-key"
      timeout-seconds: 10
  sarathi:
    api:
      url: "https://api.mock-sarathi.gov.in/dl/verify"
      key: "mock-api-key"
      timeout-seconds: 10


management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
